# Generated by Django 4.2.7 on 2024-02-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabin_type',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
