# Generated by Django 4.2.7 on 2024-02-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_cellphone_alter_customer_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cellphone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='document',
            field=models.IntegerField(unique=True),
        ),
    ]
