# Generated by Django 4.2.7 on 2024-02-15 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabin_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='static/cabin_images')),
                ('capacity', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('value', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('cabin_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cabin_type.cabin_type')),
            ],
        ),
    ]
