# Generated by Django 5.0.1 on 2024-01-29 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabin',
            old_name='price',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='cabin',
            name='publication_date',
        ),
    ]
