# Generated by Django 5.0.1 on 2024-01-31 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabin', '0003_rename_id_cabintype_cabin_id_cabin_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabin',
            old_name='id_cabin_type',
            new_name='cabin_type',
        ),
    ]
