# Generated by Django 5.0.1 on 2024-02-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin', '0004_rename_id_cabin_type_cabin_cabin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabin',
            name='image',
            field=models.ImageField(null=True, upload_to='static/cabin_images'),
        ),
    ]
