# Generated by Django 4.2.7 on 2024-02-05 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='id_customer',
            new_name='customer',
        ),
    ]
