# Generated by Django 4.2.7 on 2024-02-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='static/service_images')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('value', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
